# Generated by Django 5.0 on 2023-12-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('dist', models.IntegerField(default=0)),
                ('kf', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='cl',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='city',
            name='code',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='city',
            name='lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='city',
            name='level',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='city',
            name='lon',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='city',
            name='parent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='city',
            name='population',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='city',
            name='zoom',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='city',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='city',
            name='langs',
            field=models.ManyToManyField(to='weather.lang'),
        ),
        migrations.AddField(
            model_name='city',
            name='stations',
            field=models.ManyToManyField(to='weather.station'),
        ),
    ]
