# Generated by Django 5.0 on 2023-12-30 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_lang_station_city_cl_city_code_city_country_city_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='ids',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='station',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
