# Generated by Django 5.0 on 2023-12-30 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_station_ids_alter_station_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='stations',
        ),
        migrations.RemoveField(
            model_name='city',
            name='zoom',
        ),
        migrations.DeleteModel(
            name='Station',
        ),
    ]
