# Generated by Django 5.0 on 2023-12-30 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_remove_city_stations_remove_city_zoom_delete_station'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='langs',
        ),
        migrations.DeleteModel(
            name='Lang',
        ),
    ]
