# Generated by Django 5.0 on 2023-12-31 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_remove_city_langs_delete_lang'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='langs',
            field=models.ManyToManyField(to='weather.lang'),
        ),
    ]
